# TCL File Generated by Component Editor 16.1
# Mon Oct 25 18:35:10 CET 2018
# DO NOT MODIFY


# 
# dppsn_scheduler "Scheduler 4x1" v1.0
# Enio Kaljic 2018.10.25.18:35:10
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dppsn_scheduler
# 
set_module_property DESCRIPTION ""
set_module_property NAME dppsn_scheduler
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DPPSN
set_module_property AUTHOR "Enio Kaljic"
set_module_property DISPLAY_NAME "Scheduler 4x1"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dppsn_scheduler
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file dppsn_scheduler.vhd VHDL PATH dppsn_scheduler.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL dppsn_scheduler
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file dppsn_scheduler.vhd VHDL PATH dppsn_scheduler.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits SYMBOLS
set_interface_property csr associatedClock csr_clk
set_interface_property csr associatedReset csr_reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr bridgedAddressOffset 0
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr csr_address address Input 16
add_interface_port csr csr_read read Input 1
add_interface_port csr csr_readdata readdata Output 32
add_interface_port csr csr_write write Input 1
add_interface_port csr csr_writedata writedata Input 32
add_interface_port csr csr_waitrequest waitrequest Output 1
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point csr_clk
# 
add_interface csr_clk clock end
set_interface_property csr_clk clockRate 0
set_interface_property csr_clk ENABLED true
set_interface_property csr_clk EXPORT_OF ""
set_interface_property csr_clk PORT_NAME_MAP ""
set_interface_property csr_clk CMSIS_SVD_VARIABLES ""
set_interface_property csr_clk SVD_ADDRESS_GROUP ""

add_interface_port csr_clk csr_clk_clk clk Input 1


# 
# connection point csr_reset
# 
add_interface csr_reset reset end
set_interface_property csr_reset associatedClock csr_clk
set_interface_property csr_reset synchronousEdges DEASSERT
set_interface_property csr_reset ENABLED true
set_interface_property csr_reset EXPORT_OF ""
set_interface_property csr_reset PORT_NAME_MAP ""
set_interface_property csr_reset CMSIS_SVD_VARIABLES ""
set_interface_property csr_reset SVD_ADDRESS_GROUP ""

add_interface_port csr_reset csr_reset_reset_n reset_n Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset_n reset_n Input 1


# 
# connection point in0
# 
add_interface in0 avalon_streaming end
set_interface_property in0 associatedClock clk
set_interface_property in0 associatedReset reset
set_interface_property in0 dataBitsPerSymbol 8
set_interface_property in0 errorDescriptor ""
set_interface_property in0 firstSymbolInHighOrderBits true
set_interface_property in0 maxChannel 0
set_interface_property in0 readyLatency 0
set_interface_property in0 ENABLED true
set_interface_property in0 EXPORT_OF ""
set_interface_property in0 PORT_NAME_MAP ""
set_interface_property in0 CMSIS_SVD_VARIABLES ""
set_interface_property in0 SVD_ADDRESS_GROUP ""

add_interface_port in0 in0_data data Input 64
add_interface_port in0 in0_ready ready Output 1
add_interface_port in0 in0_valid valid Input 1
add_interface_port in0 in0_startofpacket startofpacket Input 1
add_interface_port in0 in0_endofpacket endofpacket Input 1
add_interface_port in0 in0_empty empty Input 3


# 
# connection point in1
# 
add_interface in1 avalon_streaming end
set_interface_property in1 associatedClock clk
set_interface_property in1 associatedReset reset
set_interface_property in1 dataBitsPerSymbol 8
set_interface_property in1 errorDescriptor ""
set_interface_property in1 firstSymbolInHighOrderBits true
set_interface_property in1 maxChannel 0
set_interface_property in1 readyLatency 0
set_interface_property in1 ENABLED true
set_interface_property in1 EXPORT_OF ""
set_interface_property in1 PORT_NAME_MAP ""
set_interface_property in1 CMSIS_SVD_VARIABLES ""
set_interface_property in1 SVD_ADDRESS_GROUP ""

add_interface_port in1 in1_data data Input 64
add_interface_port in1 in1_ready ready Output 1
add_interface_port in1 in1_valid valid Input 1
add_interface_port in1 in1_startofpacket startofpacket Input 1
add_interface_port in1 in1_endofpacket endofpacket Input 1
add_interface_port in1 in1_empty empty Input 3


# 
# connection point in2
# 
add_interface in2 avalon_streaming end
set_interface_property in2 associatedClock clk
set_interface_property in2 associatedReset reset
set_interface_property in2 dataBitsPerSymbol 8
set_interface_property in2 errorDescriptor ""
set_interface_property in2 firstSymbolInHighOrderBits true
set_interface_property in2 maxChannel 0
set_interface_property in2 readyLatency 0
set_interface_property in2 ENABLED true
set_interface_property in2 EXPORT_OF ""
set_interface_property in2 PORT_NAME_MAP ""
set_interface_property in2 CMSIS_SVD_VARIABLES ""
set_interface_property in2 SVD_ADDRESS_GROUP ""

add_interface_port in2 in2_data data Input 64
add_interface_port in2 in2_ready ready Output 1
add_interface_port in2 in2_valid valid Input 1
add_interface_port in2 in2_startofpacket startofpacket Input 1
add_interface_port in2 in2_endofpacket endofpacket Input 1
add_interface_port in2 in2_empty empty Input 3


# 
# connection point in3
# 
add_interface in3 avalon_streaming end
set_interface_property in3 associatedClock clk
set_interface_property in3 associatedReset reset
set_interface_property in3 dataBitsPerSymbol 8
set_interface_property in3 errorDescriptor ""
set_interface_property in3 firstSymbolInHighOrderBits true
set_interface_property in3 maxChannel 0
set_interface_property in3 readyLatency 0
set_interface_property in3 ENABLED true
set_interface_property in3 EXPORT_OF ""
set_interface_property in3 PORT_NAME_MAP ""
set_interface_property in3 CMSIS_SVD_VARIABLES ""
set_interface_property in3 SVD_ADDRESS_GROUP ""

add_interface_port in3 in3_data data Input 64
add_interface_port in3 in3_ready ready Output 1
add_interface_port in3 in3_valid valid Input 1
add_interface_port in3 in3_startofpacket startofpacket Input 1
add_interface_port in3 in3_endofpacket endofpacket Input 1
add_interface_port in3 in3_empty empty Input 3


# 
# connection point out
# 
add_interface out avalon_streaming start
set_interface_property out associatedClock clk
set_interface_property out associatedReset reset
set_interface_property out dataBitsPerSymbol 8
set_interface_property out errorDescriptor ""
set_interface_property out firstSymbolInHighOrderBits true
set_interface_property out maxChannel 0
set_interface_property out readyLatency 0
set_interface_property out ENABLED true
set_interface_property out EXPORT_OF ""
set_interface_property out PORT_NAME_MAP ""
set_interface_property out CMSIS_SVD_VARIABLES ""
set_interface_property out SVD_ADDRESS_GROUP ""

add_interface_port out out_data data Output 64
add_interface_port out out_empty empty Output 3
add_interface_port out out_endofpacket endofpacket Output 1
add_interface_port out out_ready ready Input 1
add_interface_port out out_startofpacket startofpacket Output 1
add_interface_port out out_valid valid Output 1
add_interface_port out out_channel channel Output 128

